# Site settings
title: Nicholas Utikal
header-img: "img/night-run.jpg"
email: nicholasutikal@gmail.com
description: "A Professional Blog and Website"
baseurl: ""
url: "http://nichohelmut.github.io"
github_username:  nichohelmut
facebook_username:  Nicholas Utikal

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
paginate_path: "blog/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
